### ISSUE TITLE
CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by kelvz-hub** [advanced-cropper/vue-advanced-cropper#209] opened 2022-08-17 10:06 UTC
Hi I used advanced-cropper to crop image from amazon s3 bucket but CORS policy issue shown.
Is there another way to do this? 
![image](https://user-images.githubusercontent.com/65855586/185092964-a8a09c7c-a60a-4c35-b60e-20601791ebd6.png)

**Comment by Norserium** [comment] 2022-08-17 10:28
@kelvz-hub, is [this guide](https://advanced-cropper.github.io/vue-advanced-cropper/guides/cross-origin.html#how-does-it-relate-to-cropper) can be helpful for you?

**Comment by kelvz-hub** [comment] 2022-08-17 10:43
> @kelvz-hub, does [this guide](https://advanced-cropper.github.io/vue-advanced-cropper/guides/cross-origin.html#how-does-it-relate-to-cropper) answer on your question?

It works when the image is from local computer but my problem is I get the image from s3 bucket

**Comment by Norserium** [comment] 2022-08-17 10:52
@kelvz-hub, well, it's the common issue with AWS. Try to set CORS configuration on that side correctly: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors-troubleshooting.html.

**Comment by kelvz-hub** [comment] 2022-08-17 11:35
> @kelvz-hub, well, it's the common issue with AWS. Try to set CORS configuration on that side correctly: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors-troubleshooting.html.
> 
> The guide answers why it happens.

I set cors config in s3 bucket but not working
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "GET"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": [
            "Access-Control-Allow-Origin"
        ],
        "MaxAgeSeconds": 3000
    }
]

**Comment by Norserium** [comment] 2022-08-17 12:01
1. Check that your link opens in the browser.
2. Try to set the following config for CORS policy:
```
[
    {
        "AllowedHeaders": [
            "*"
        ],
        "AllowedMethods": [
            "POST",
            "GET",
            "PUT",
            "DELETE",
            "HEAD"
        ],
        "AllowedOrigins": [
            "*"
        ],
        "ExposeHeaders": []
    }
]
```

**Comment by Norserium** [comment] 2022-08-17 15:01
@kelvz-hub

**Comment by kelvz-hub** [comment] 2022-08-18 01:38
> [
>     {
>         "AllowedHeaders": [
>             "*"
>         ],
>         "AllowedMethods": [
>             "POST",
>             "GET",
>             "PUT",
>             "DELETE",
>             "HEAD"
>         ],
>         "AllowedOrigins": [
>             "*"
>         ],
>         "ExposeHeaders": []
>     }
> ]

i tried but no luck

**Comment by Norserium** [comment] 2022-08-18 08:34
@kelvz-hub, does the passed link opens in the browser? Try to click at the link in the error.

**Comment by kelvz-hub** [comment] 2022-08-18 14:01
> ```
> :canvas="false"
> ```

Hi thanks for the reply the image show but i cant get the cropped image now the error is "Error in v-on handler: "TypeError: Cannot read properties of undefined (reading 'toDataURL')"" and my code when crop button clicked is:

const result = this.$refs.cropper.getResult();
const crop = result.canvas.toDataURL(
    "image/jpg"
);

**Comment by kelvz-hub** [comment] 2022-08-19 02:35
> @kelvz-hub, if you set `canvas` to false, the canvas won't be available, so you can't get the cropped image. It's okay, it was just for check.
> 
> Could you remove that property and send me the details of the image loading request? Like this: ![image](https://user-images.githubusercontent.com/9862719/185428241-a25d74a0-3731-4f59-9934-899c3e9fa1ab.png)
> 
> Hide the private headers, by the way.
Here's the result
![image](https://user-images.githubusercontent.com/65855586/185530570-e1e98393-15a1-4f21-a706-11efae8006d8.png)

**Comment by Norserium** [comment] 2022-08-19 08:36
@kelvz-hub, look, there is no `Access-Control-Allow-Origin` header. The problem on the storage configuration side. Try to check the section "[Troubleshooting CORS methods](https://aws.amazon.com/premiumsupport/knowledge-center/s3-configure-cors/)".

**Comment by kelvz-hub** [comment] 2022-08-19 10:24
> @kelvz-hub, look, there is no `Access-Control-Allow-Origin` header. The problem on the storage configuration side. Try to check the section "[Troubleshooting CORS methods](https://aws.amazon.com/premiumsupport/knowledge-center/s3-configure-cors/)".

![image](https://user-images.githubusercontent.com/65855586/185599043-f12a6a62-1a04-4ab1-8e56-5fcc685bac7e.png)
It shows that I configured it correctly

**Comment by kelvz-hub** [comment] 2022-08-19 10:26
> @kelvz-hub, look, there is no `Access-Control-Allow-Origin` header. The problem on the storage configuration side. Try to check the section "[Troubleshooting CORS methods](https://aws.amazon.com/premiumsupport/knowledge-center/s3-configure-cors/)".

![image](https://user-images.githubusercontent.com/65855586/185599367-f0d06da2-207c-4c0d-90cf-bb5a9791eb00.png)
It shows that i configured it correctly

**Comment by Norserium** [comment] 2022-08-19 10:52
@kelvz-hub, it's definitely strange. Try to use that image in [the sandbox](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w).

**Comment by kelvz-hub** [comment] 2022-08-20 13:30
> @kelvz-hub, it's definitely strange. Try to use that image in [the sandbox](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w).

Hi, I have an update to this issue I passed query parameter as part of the image url like this https://image/folder/test.png?test=true and it works

**Comment by Norserium** [comment] 2022-08-20 13:32
@kelvz-hub, it looks like your image was cached before you set the correct CORS settings at the Amazon Storage.

**Comment by Norserium** [comment] 2022-08-20 13:33
Try to reproduce the error in the private mode.

**Comment by kelvz-hub** [comment] 2022-08-20 13:39
> Try to reproduce this issue in the private browsing mode.

I tried it in google incognito but also show cors issue without the query parameter. The strange part is when i change the word "test" to any word the trick is not working so i stay to use "test" as my query param for every images

**Comment by Norserium** [comment] 2022-08-20 17:06
@kelvz-hub, I've tried your image in the sandbox and it works.

![image](https://user-images.githubusercontent.com/9862719/185758490-ef299c56-0218-41b9-84c5-88d8690b473d.png)

Could you provide the screenshot of response headers for both image requests?

**Comment by kelvz-hub** [comment] 2022-08-22 05:29
> @kelvz-hub, I've tried your image in the sandbox and it works without any query parameters.
> 
> ![image](https://user-images.githubusercontent.com/9862719/185758490-ef299c56-0218-41b9-84c5-88d8690b473d.png)
> 
> Could you provide the screenshot of response headers for both image requests?

yes I also tried it in the sandbox and it works only in my end is not working

**Comment by Norserium** [comment] 2022-08-22 10:22
@kelvz-hub, well it's strange. Does it work with any query parameter on your side? Did you try to reproduce this issue in an another browser?

**Comment by Norserium** [comment] 2022-08-22 10:23
Cold you send me the response headers for both image request when this issue is reproduced?

**Comment by Norserium** [comment] 2022-08-28 09:46
@kelvz-hub, any news?

**Comment by kelvz-hub** [comment] 2022-09-26 12:00
> > @kelvz-hub, it's definitely strange. Try to use that image in [the sandbox](https://codesandbox.io/s/vue-avanced-cropper-basic-jfy5w).
> 
> Hi, I have an update to this issue I passed query parameter as part of the image url like this https://image/folder/test.png?test=true and it works but i want to know why this works

@Norserium I used this solution

**Comment by Norserium** [comment] 2022-09-26 13:56
@kelvz-hub, it's barely solution, because we don't know why it works. Anyway, I close this issue, but feel free to reopen it if the issue returns.

**Closed by Norserium** 2022-09-26 13:56 UTC

**Comment by vlad909** [comment] 2023-02-14 10:35
its's very strange solultion, guys

**Comment by Norserium** [comment] 2023-02-14 11:05
@vlad909, did you encounter the same issue?

**Comment by vlad909** [comment] 2023-02-14 11:29
@Norserium hello. oh yes. i've disable canvas option. it's work. i don't know what's going on. it's perfectly works in dev server with canvas, but production is broken. I tried to find a problem with nginx, but it's not that it's not that critically different from dev

**Comment by Norserium** [comment] 2023-02-14 12:35
@vlad909, I assume that you use a proxy in the development environment so you bypass cross origin troubles by this way. Do you?

**Comment by Norserium** [comment] 2023-02-14 12:37
In any case I'm sure that it's the server configuration issue, I've described the details in [the guide](https://advanced-cropper.github.io/vue-advanced-cropper/guides/cross-origin.html).

If you need help in its resolution send the nginx configs + image request response headers (for development and production).

**Comment by theo-bittencourt** [comment] 2023-10-11 19:55
> @kelvz-hub, it looks like your image was cached before you set the correct CORS settings at the Amazon Storage.

Having this issue as well. Seems it is caused by browser cache, indeed.


### First request
![International Brazilian Jiu-Jitsu Federation_hWegxChp](https://github.com/advanced-cropper/vue-advanced-cropper/assets/405703/6d81b929-9a88-4438-8fd3-56e0d84ad3c4)

### Second request
![International Brazilian Jiu-Jitsu Federation_4NLjepCX](https://github.com/advanced-cropper/vue-advanced-cropper/assets/405703/f32e4685-ed97-4918-96c9-3fc70097c7f2)

**Comment by theo-bittencourt** [comment] 2023-10-11 21:50
Fixed here.  Just added `crossorigin` attr on `<img>` that we utilized for "preview" (before crop activation). That preview was responsible for the first request, that was being cached because we didn't define `crossorigin` before.

**Comment by mattpepin-funeraweb** [comment] 2024-10-29 13:34
Fixed it by patching image.ts, replacing XmlHttpRequest with fetch and forcing a reload:

```
					fetch(img, {
						cache: 'reload'
					}).then(response => {
						if (response.ok) {
							return response.arrayBuffer();
						} else {
							reject('Error: invalid response');
						}
					}, reject).then(buffer => resolve(buffer), reject);
```
