### ISSUE TITLE
[Violation] Warning: Added non-passive event listener

### ISSUE THREAD

**Issue by Psycarlo** [advanced-cropper/vue-advanced-cropper#231] opened 2023-01-31 12:42 UTC
Getting this warning:

`[Violation] Added non-passive event listener to a scroll-blocking <algum> evento. Consider marking event handler as 'passive' to make the page more responsive. See <URL>`

Versions:
"vue": "^3.2.16"
"vue-advanced-cropper": "^2.8.8"
"vite": "^4.0.1"

**Comment by Psycarlo** [comment] 2023-02-01 17:42
What if we changed events from `passive: false` to `passive: true`?
@Norserium

**Comment by Norserium** [comment] 2023-02-01 22:50
@Psycarlo, thank you for your notice. I need to investigate this aspect. I will try to do it on weekends.

**Comment by Psycarlo** [comment] 2023-02-02 20:17
Nice! Let me know if you want to make the change. If so, I can create the PR

**Comment by Norserium** [comment] 2023-02-03 20:41
@Psycarlo, how to reproduce the appearing of this warning?

**Comment by Psycarlo** [comment] 2023-02-03 21:27
@Norserium 

Create a new vue app: `npm init vue@latest`
Install vue-advanced-cropper v2.8.8

Add Cropper
`<Cropper
    ref="cropper"
    src="https://images.unsplash.com/photo-1516007445015-fc20d86f8468?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80"
    :stencil-component="RectangleStencil"
  />`

Run dev server

Open console
`[Violation] Added non-passive event listener to a scroll-blocking <algum> evento. Consider marking event handler as 'passive' to make the page more responsive. See <URL>`

**Comment by Norserium** [comment] 2023-02-03 22:25
@Psycarlo , thank you, I reproduced the appearing of this warning.

But there is the reason, why this event listeners are marked as not passive. They should be prevented. The most clear example is the preventing of the mobile pinch gesture to implement the image zoom, otherwise they will conflict.

Of course, I can use `touch-action: none`, but [its support is limited](https://caniuse.com/?search=touch-action).

Any ideas? Did you see any solid cropper that uses passive events?

**Comment by Psycarlo** [comment] 2023-02-03 23:01
I did not.
Maybe could we have an option to turn on/off `touch-action`?

Or I will just keep living my life looking at the warning 😄 -- and that is fine

**Comment by Norserium** [comment] 2023-02-04 08:49
@Psycarlo, try to open [Google Maps](https://www.google.com/maps) and look in the console window.

**Closed** 2023-02-05 13:32 UTC
